# Generated by Django 4.0.6 on 2022-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('passport', models.ImageField(db_index=True, upload_to='', verbose_name='Passport')),
                ('date', models.CharField(max_length=300, verbose_name='Exam date')),
                ('bc', models.CharField(max_length=100, verbose_name='BC or IDP')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('exam', models.CharField(max_length=300, verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Register exam',
                'verbose_name_plural': 'Register exam',
            },
        ),
    ]
